from typing import TypedDict

class TranslatorOptions(TypedDict, total=False):
    ace_Arab: str
    ace_Latn: str
    acm_Arab: str
    acq_Arab: str
    aeb_Arab: str
    afr_Latn: str
    ajp_Arab: str
    aka_Latn: str
    amh_Ethi: str
    apc_Arab: str
    arb_Arab: str
    arb_Latn: str
    ars_Arab: str
    ary_Arab: str
    arz_Arab: str
    asm_Beng: str
    ast_Latn: str
    awa_Deva: str
    ayr_Latn: str
    azb_Arab: str
    azj_Latn: str
    bak_Cyrl: str
    bam_Latn: str
    ban_Latn: str
    bel_Cyrl: str
    bem_Latn: str
    ben_Beng: str
    bho_Deva: str
    bjn_Arab: str
    bjn_Latn: str
    bod_Tibt: str
    bos_Latn: str
    bug_Latn: str
    bul_Cyrl: str
    cat_Latn: str
    ceb_Latn: str
    ces_Latn: str
    cjk_Latn: str
    ckb_Arab: str
    crh_Latn: str
    cym_Latn: str
    dan_Latn: str
    deu_Latn: str
    dik_Latn: str